//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KingAndJokeEntities1 : DbContext
    {
        public KingAndJokeEntities1()
            : base("name=KingAndJokeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorRequests> AuthorRequests { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BookLists> BookLists { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Freezes> Freezes { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<ReportTypes> ReportTypes { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnfreezeRequests> UnfreezeRequests { get; set; }
        public virtual DbSet<UserBookLists> UserBookLists { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
