//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBookLists
    {
        public int UserId { get; set; }
        public int BookId { get; set; }
        public Nullable<int> ListId { get; set; }
    
        public virtual BookLists BookLists { get; set; }
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
